# Generated by Django 3.2.17 on 2023-02-09 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'discounts',
                'verbose_name_plural': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stripe_product_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'items',
                'verbose_name_plural': 'item',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxation', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.items')),
            ],
            options={
                'verbose_name': 'goods tax',
                'verbose_name_plural': 'tax',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.discount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.items')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.tax')),
            ],
            options={
                'verbose_name': 'orders',
                'verbose_name_plural': 'order',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.items'),
        ),
    ]
