# Generated by Django 3.2.17 on 2023-02-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='stripe_product_id',
        ),
    ]
