# Generated by Django 3.2.17 on 2023-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_items_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
